import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const revalidate: number = 20
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

	  <html lang="en">
	  <head>
		  <link rel="icon" href="/favicon.ico" sizes="any"/>
		  <title>Gitlab pipelines dashboard</title>
	  </head>
	  <body className="bg-white">
	  <div className="navbar bg-base-100">
	  <Image
			  src="/images/logo.png"
			  width={200}
			  height={80}
			  alt="left"
			  className="mx-auto mt-5"
		  />
	  </div>
	  {children}</body>
	  </html>
  )
}
